services:
  - type: web
    name: pi-collision-backend
    env: node
    plan: free
    region: oregon
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: PORT
        value: "3001"
